
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Navbar";
import Providers from "@/Provider/Provider";
import TanstackProvider from "@/TanstackProvider/page";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "JobNest",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
      <TanstackProvider>
        <Providers>
            <nav className="w-full z-50 fixed top-0 right-0 left-0  text-[#F9FAFB]">
              <Navbar></Navbar>
            </nav>
            <main className="">
              
              {children}
            </main>
        </Providers>
        </TanstackProvider>
      </body>

    </html>
  );
}
