import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "JobNest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-[100%] fixed top-0 right-0 left-0 bg-[#0F172A] text-[#F9FAFB]">
          <Navbar></Navbar>
        </nav>
        <main className="">
          <div className="w-[100%] h-[65px]"></div>
          {children}
        </main>
      </body>
    </html>
  );
}
